In [4]:
from sklearn.datasets import load_iris


In [7]:
dataset = load_iris()
dataset

print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [9]:
dataset.keys()


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

# Making  DataFrame

In [12]:
import pandas as pd
import numpy as np

df = pd.DataFrame(dataset.data , columns = dataset.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [13]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

# Adding new column name target to the Data Frame

In [14]:
df['target'] = dataset.target

In [15]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

## Seeing classification

In [16]:

dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Insights
### multiclassification

## So we convert the Classifiaction into the Binary

## Binary Classification 

In [27]:
df_copy= df[df['target']!= 2]


In [23]:
df_copy.target

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: target, Length: 100, dtype: int32

# Independent and Dependent Features

In [26]:
X = df_copy.iloc[:,:-1]  ## remove the last column 
y = df_copy.iloc[:,-1]

### <center> Print X and y

In [29]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [30]:
y

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: target, Length: 100, dtype: int32

## <center>Train , Test, Split

In [31]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size =20,random_state =35)

# <center>Logistic Regression

In [33]:
from sklearn.linear_model import LogisticRegression

## make classifier

classifier = LogisticRegression()



In [34]:
## fit the model to the data

classifier.fit(X_train,y_train)


LogisticRegression()

## prediction


In [35]:
## predict the probability of each dataset

classifier.predict_proba(X_test)


array([[0.9838255 , 0.0161745 ],
       [0.02226207, 0.97773793],
       [0.22748058, 0.77251942],
       [0.9751361 , 0.0248639 ],
       [0.00383401, 0.99616599],
       [0.96515525, 0.03484475],
       [0.97702818, 0.02297182],
       [0.94681687, 0.05318313],
       [0.00774382, 0.99225618],
       [0.98469164, 0.01530836],
       [0.99013585, 0.00986415],
       [0.9601993 , 0.0398007 ],
       [0.00161229, 0.99838771],
       [0.97798597, 0.02201403],
       [0.02339378, 0.97660622],
       [0.98078605, 0.01921395],
       [0.96499098, 0.03500902],
       [0.00365839, 0.99634161],
       [0.02434066, 0.97565934],
       [0.02206228, 0.97793772]])

### Or Another way of Prediction

In [37]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1])

## Confusion Matrix, Accuracy Score , Classification Report


#### Confusion matrix betweem  Y_pred and Y_test

In [41]:
from sklearn.metrics import confusion_matrix ,accuracy_score,classification_report



In [44]:
# confusion matrix
print(confusion_matrix(y_pred,y_test))

# accuracy Score
print(accuracy_score(y_pred,y_test))

# classification Score

print(classification_report(y_pred,y_test))

[[11  0]
 [ 0  9]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00         9

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## Insights from Confuion matrix , accuracy and classifiaction report

- Accuray is 100% 


## <center> <bottom> Hyprerparameter Tunning

In [46]:
## Grid Search CV

from sklearn.model_selection import GridSearchCV

import warnings
warnings.filterwarnings('ignore')


In [51]:
parameters = {'penalty' :('l1','l2','elasticnet',None), 'C' :[1,10,20]}


In [59]:
clf = GridSearchCV(classifier , param_grid= parameters ,cv = 10)



## Splitting of Train Data to Validation data

In [60]:
clf.fit(X_train,y_train)


GridSearchCV(cv=10, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

### Check combination of C and Penality to obtain best result

In [66]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [75]:
classifier=LogisticRegression(C=1,penalty='l2')

In [76]:
classifier.fit(X_train,y_train)

LogisticRegression(C=1)

In [77]:
## prediction

y_pred = classifier.predict(X_test)
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1])

### Print the Confusion matrix , accuracy score, classifiaction_report

In [79]:

print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))
print(classification_report(y_pred, y_test))


[[11  0]
 [ 0  9]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00         9

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



# <center> RandomizedSearch Cv

In [69]:
from sklearn.model_selection import RandomizedSearchCV

random_clf = RandomizedSearchCV(LogisticRegression(), param_distributions=parameters, cv = 10)


In [73]:
# fit the model
random_clf.fit(X_train, y_train)


RandomizedSearchCV(cv=10, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [74]:
random_clf.best_params_

# combinations


{'penalty': 'l2', 'C': 1}

## <center>Logistics Regression using the randomizedSearch Cv

In [82]:
classifier = LogisticRegression(C = 1,penalty = 'l2')
classifier.fit(X_train,y_train)


LogisticRegression(C=1)

In [88]:
## prediction 

print(accuracy_score(y_pred, y_test))
print("\n")
print(confusion_matrix(y_pred, y_test))
print("\n")

print(classification_report(y_pred, y_test))

1.0


[[11  0]
 [ 0  9]]


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00         9

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

